apiVersion: apps/v1
kind: Deployment
metadata:
  name: medilab
  namespace: test-ns
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: medilab
  template:
    metadata:
      labels:
        app: medilab
    spec:
      containers:
      - name: medilab
        image: yrr03/medilab:TAG
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medilabsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: medilab
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
